apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: postgres
  namespaceSelector:
    matchNames:
      - application
  endpoints:
    - port: tcp
      interval: 15s
