image:
  repository: shreg10/backend
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

config:
  APP_ENV: dev

secret:
  DB_PASSWORD: devpass

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpu: 50
